### ISSUE TITLE
Some additional configurability

### ISSUE THREAD

**Issue by ilg-ul** [jsnyder/arm-eabi-toolchain#15]
I created a script to automatically build the toolchain for Mac OS X

In order to allow builds with different paths for the libraries, and also to facilitate testing, I applied a patch to your Makefile.

Basically it allows that most of the configuration to be transmitted via environment variables.

If you think useful, you can apply it to your master version.

The script is available at 

http://gnuarmeclipse.svn.sourceforge.net/viewvc/gnuarmeclipse/trunk/scripts/arm-cs-tools-build.sh

Some details on using it are available at

http://gnuarmeclipse.sourceforge.net/wiki/Toolchain_installation#Sourcery_CodeBench_Lite_Edition

Regards,

Liviu

**Comment by jsnyder** [comment]
Thanks for the patch, I've applied it.  I couldn't quickly find an email address to associate with the commit, so I just thanked/credited in the commit message.

**Comment by ilg-ul** [comment]
Thanks, I updated my profile to show the email address and other details.

Liviu
