### ISSUE TITLE
The reasons behind the Linux version?

### ISSUE THREAD

**Issue by ilg-ul** [jsnyder/arm-eabi-toolchain#17]
James, 

Can you help me understand the reasons behind maintaining the Makefile to run on Linux?

I recently installed the latest CodeSourcery IA32 GNU/Linux TAR (the advanced package) on a 64bit Ubuntu 11.10 and (at least apparently) had no problems.

Is there anything wrong with their distribution that you fixed?

Liviu

**Comment by jsnyder** [comment]
On Jan 18, 2012, at 3:35, Liviu Ionescureply@reply.github.com wrote:

> James, 
> 
> Can you help me understand the reasons behind maintaining the Makefile to run on Linux?

It's fairly easy once it works on OS X. Also given that the build takes a while I have an 8 core Linux box that's quicker to iterate on than my Mac laptop for initial build testing. 

Also as mentioned, I build newlib with a few optimizations geared towards code size, so I like having the same chain on both platforms.

> I recently installed the latest CodeSourcery IA32 GNU/Linux TAR (the advanced package) on a 64bit Ubuntu 11.10 and (at least apparently) had no problems.
> 
> Is there anything wrong with their distribution that you fixed?

Not really. It now matches their build settings even more closely aside from the newlib flags being a little different. I had to just adjust a few things to accommodate some changed build dependencies for gcc 4.6 and turning on LTO.

**Comment by ilg-ul** [comment]
> an 8 core Linux box that's quicker...

ah, ok, that's a good reason.

> I build newlib with a few optimizations geared towards code size, so I like having the same chain on both platforms.

how complicated would be to add a switch to either apply these optimisations, or revert exactly to the settings used by CodeSourcery versions?

Liviu
