### ISSUE TITLE
git description

### ISSUE THREAD

**Issue by ilg-ul** [jsnyder/arm-eabi-toolchain#26]
I updated my build script to use the latest version (it works fine), and I also updated it to clone the repos instead of fetching the archive.

after this change I noticed the PKG_VERSION looks unusual, for example:

```
gcc version 4.6.3 (32-bit ARM EABI Toolchain CS-2012.03-56-v2011.09-69-17-ge3f4013) 
```

I checked and the last part comes from the output of 'git description'

```
v2011.09-69-17-ge3f4013
```

I personally consider this not very usefull, since, as can be seen here, it is out of date.

so I applied a small patch, to make the BUILD_ID also externally configurable:

```
--- Makefile    2012-10-30 21:56:07.000000000 +0200
+++ ../../Makefile  2012-10-30 21:56:42.000000000 +0200
@@ -66,7 +66,7 @@


 ####    BUILD LABELING / TAGGING      #####
-BUILD_ID   = $(shell git describe --always)
+BUILD_ID   ?= $(shell git describe --always)
 TODAY           = $(shell date "+%Y%m%d")

 ifeq ($(strip $(BUILD_ID)),)
```

in my script I initialise it with the short git id:

```
export BUILD_ID="e3f4013"
```

if you think useful, you can use this patch in your next release.

regards,

Liviu

**Comment by jsnyder** [comment]
Thanks.  I've been somewhat busy and just included the updated version but didn't update the tags.  I'll try and come up with something cleaner when I get around to some work on this again.
