### ISSUE TITLE
build fails

### ISSUE THREAD

**Issue by ilg-ul** [jsnyder/arm-eabi-toolchain#3]
It seems the make attempts to build more files than needed:

In file included from /Users/ilg/Work/Sourcery2/jsnyder-arm-eabi-toolchain-3c6734f/newlib-2010q1/newlib/libc/include/wctype.h:5,
                 from ../../../../../../../newlib-2010q1/newlib/libc/ctype/iswalnum.c:30:
/Users/ilg/Work/Sourcery2/jsnyder-arm-eabi-toolchain-3c6734f/newlib-2010q1/newlib/libc/include/sys/_types.h:63: fatal error: stddef.h: No such file or directory
compilation terminated.
make[9]: **\* [lib_a-iswalnum.o] Error 1
make[9]: **\* Waiting for unfinished jobs....

**Comment by jsnyder** [comment]
I believe this should now be fixed in the latest version committed.

After updating, you may wish to do a "make clean" before trying again.

**Comment by ilg-ul** [comment]
thanks, it's fine now.

I made a reference to your code, in my project's wiki:

https://sourceforge.net/apps/mediawiki/gnuarmeclipse/index.php?title=Toolchain_installation

any comments/suggestions are welcome.

regards,

Liviu

**Comment by jsnyder** [comment]
Thanks for the heads-up.  I'll check out your project as well, though I don't generally use Eclipse.
