### ISSUE TITLE
Build fails on OS X 10.10

### ISSUE THREAD

**Issue by fakufaku** [jsnyder/arm-eabi-toolchain#37]
When compiling on OS X 10.10, the configuration fails with the following error message

```
couldn't understand kern.osversion `14.0.0'
```

The workaround I found (as suggested in this [thread](https://github.com/sstephenson/ruby-build/issues/654)) was to add the following build option

```
MACOSX_DEPLOYMENT_TARGET=10.9
```

**Comment by jsnyder** [comment]
Thanks for the heads-up. Did you find that was necessary only for specific targets or did you set that variable for the whole build?:
i.e.:
MACOSX_DEPLOYMENT_TARGET=10.9 make cross-install

**Comment by jsnyder** [comment]
As another note, I'm not actually getting this happening for me. Either on the 2014.05 that I've just updated to or on the 2013.05 that was in the master branch at the time you posted this.

I've got XCode 6.1.1 on Mac OS X 10.10.1.

**Comment by fakufaku** [comment]
I have XCode 6.1.1 (6A2008a) and Mac OS X 10.10.1

Last time I tried I was at commit f7adea7e89d94 of the master branch.

I have now pulled the HEAD (3f93944597c141ccb89a8e37ee8cce6ccdc61ed5) of the repository and it compiles without problem.
