### ISSUE TITLE
Bad checksum

### ISSUE THREAD

**Issue by ilg-ul** [jsnyder/arm-eabi-toolchain#8]
I encountered a small problem with the checksum validation code:

sudo make cross-gcc
7c302162ec813d039b8388bd7d2b4176 7c302162ec813d039b8388bd7d2b4176
Bad Checksum! Please remove the following file and retry: arm-2011.03-42-arm-none-eabi.src.tar.bz2

I tried adding some additional quotes, plus a debug line, and (as seen before) the checksum seems ok.

the code now reads, I'm afraid the logical operators might have a problem:

downloadsrc: $(LOCAL_SOURCE)
    @(t1=`openssl md5 $(LOCAL_SOURCE) | cut -f 2 -d " " -` && \
    echo "$$t1" "$(SOURCE_MD5_CHCKSUM)" && \
    test "$$t1" = "$(SOURCE_MD5_CHECKSUM)" || \
    echo "Bad Checksum! Please remove the following file and retry: $(LOCAL_SOURCE)")

Could you check?

Regards,

Liviu

**Comment by ilg-ul** [comment]
Oops!

I saw the other bug ticked. I removed the spaces and it is ok now.

Could you update the Makefile?

Liviu

**Comment by jsnyder** [comment]
Sure. I'll commit a fix for that shortly.

Just noticed that apparently I didn't have email notifications on for when issues are added here. I'll try and fix these couple minor outstanding issues.

**Comment by jsnyder** [comment]
Closing since there was already an open issue for this.
